### ISSUE TITLE
Theme option in settings / SearX support

### ISSUE THREAD

**Issue by danielyrovas** [Fivefold/linkding-injector#2]
It would be great if there could be a dark/light theme option in the addon settings.
Additionally how much work would it be to support a search engine like SearX?

**Comment by Fivefold** [comment]
> It would be great if there could be a dark/light theme option in the addon settings. 

I will try to add dark/light/automatic theme options for the next update.

> Additionally how much work would it be to support a search engine like SearX?

I'm not familiar with SearX but from what I see it's mainly intended to be self-hosted. There are lots of public instances too. The problem is that I need to specify the pages the content script is injected into in the extension's manifest.json. This can't be changed at runtime, e.g. for specifying the URL of your SearX instance yourself.

Since a SearX instance could be hosted at *any* URL and public instances found [here](https://searx.space/#) also vary wildly in their URLs (and even use different themes) I don't see a way of properly supporting SearX. 

If you know basic javascript and css you could add support for *your* instance yourself by forking the project and putting the URL of your own SearX instance into the manifest.json. I can give you further instructions if interested.

**Comment by danielyrovas** [comment]
Hmm yes I can see the code.
> This can't be changed at runtime, e.g. for specifying the URL of your SearX instance yourself.

So we couldn't make an option in preferences to add URLS to inject the link into?
Thanks for the awesome extension!

**Comment by Fivefold** [comment]
> So we couldn't make an option in preferences to add URLS to inject the link into?

I'm afraid not. The content script (which injects/creates the results box in the search page) can only be injected into pages pre-defined in the manifest.json (see [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts#matching_url_patterns))

The only way I can think of is injecting the content script into *all* pages and then actually do someting within the script depending on the URL. I don't think this is worth it though due to security concerns.

---

Regarding adding a URL yourself by forking the extension:

You need to add a block like this containing your SearX URL. You could also just add it in line 22. See the link above for a match pattern reference.
https://github.com/Fivefold/linkding-injector/blob/fdb713bd3af7f47497dd561a54d4d94ca5e3f8b8/manifest.json#L21-L25

Then you'd need to add relevant code in the content script:
https://github.com/Fivefold/linkding-injector/blob/fdb713bd3af7f47497dd561a54d4d94ca5e3f8b8/src/searchInjection.js#L22-L26

As well as here:

https://github.com/Fivefold/linkding-injector/blob/fdb713bd3af7f47497dd561a54d4d94ca5e3f8b8/src/searchInjection.js#L117-L122

For the querySelector you'd need to find the relevant sidebar div css class or ideally id to inject into (easily found using right-click and inspect on your SearX page).

This should get the injection working, the rest is CSS styling.

To test or use your personalized extension see [here](https://github.com/Fivefold/linkding-injector#manual-installation).

**Comment by danielyrovas** [comment]
Thanks for your help, I will try out the fork route.

**Comment by Fivefold** [comment]
Sure! If you get stuck feel free to ask.

**Comment by danielyrovas** [comment]
So I have successfully got the extension working inside brave (through load unpacked) but I'm not sure how to load it into firefox. If I load the `web-ext-artifacts/linkding_injector-1.1.0.zip` as an addon file it fails (corrupt). I tried with both the build script and `web-ext build --overwrite-dest` zip file.

**Comment by Fivefold** [comment]
For testing and development in firefox you can also just open the _manifest.json_ in the source directory via about:debugging and "Load Temporary Add-on" and selecting the _manifest.json_.

Loading the packaged extension (zip file) should work just as well though. I attached the zip I get via `./build.ps1` (on a Windows machine). See if you can load this and if you have any differences. If you are on Linux it might be a permission issue.

[linkding_injector-1.1.0.zip](https://github.com/Fivefold/linkding-injector/files/8798990/linkding_injector-1.1.0.zip)

**Comment by Fivefold** [comment]
Opened a new issue just for SearX support. It might happen after all. Watch https://github.com/Fivefold/linkding-injector/issues/9 for any news.

**Comment by danielyrovas** [comment]
Thanks for your help. I did manage to get the Firefox addon working and I was using that until now :)
